/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mvc_example.View;

import com.mycompany.mvc_example.Controller.ContadorController;
import com.mycompany.mvc_example.Model.ContadorModel;
import com.mycompany.mvc_example.Model.Observer;

import javax.swing.*;

/**
 *
 * @author T-Gamer
 */
public class ContadorView extends javax.swing.JFrame implements Observer {

    private final ContadorModel model;

    public ContadorView(ContadorModel model) {
        this.model = model;
        initComponents();
        update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelValor = new javax.swing.JLabel();
        botaoIncrementar = new javax.swing.JButton();
        botaoDecrementar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelValor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelValor.setText("Valor: 0");
        labelValor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        botaoIncrementar.setText("+");

        botaoDecrementar.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoDecrementar)
                            .addComponent(botaoIncrementar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(labelValor)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(labelValor)
                .addGap(29, 29, 29)
                .addComponent(botaoIncrementar)
                .addGap(37, 37, 37)
                .addComponent(botaoDecrementar)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void update() {
        System.out.println("View: Recebi uma notificação. Atualizando a exibição.");
        labelValor.setText("Valor: " + model.getValor());
    }
    
    public void setController(ContadorController controller) {
        botaoIncrementar.addActionListener(e -> controller.incrementarValor());
        botaoDecrementar.addActionListener(e -> controller.decrementarValor());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDecrementar;
    private javax.swing.JButton botaoIncrementar;
    private javax.swing.JLabel labelValor;
    // End of variables declaration//GEN-END:variables
}
